# -*- coding: utf-8 -*-
"""
Created on Thu Jan  9 15:27:23 2025

@author: xuefei.lu

# Generate plots for German credit case, counterfacuals generated by DiCE: 
# Figure 6 Absolute Feasible Shapley for Male and Female
# Figure 7 (a) Beewarm Feasible Shapley
# Figure 7 (b) SHAPs
# Figure 13 infeasible points/ nr of feature changed - counterfactual generated by DiCE
# Figure 17 Absolute Feasible Shapley for Age<=30 or Age >30
# Figure 20 Absolute Feasible Shapley for Single and Not Single
# Figure 21 Absolute Feasible Shapley for Rent a house, not rent
"""



import os
path = 'C:\\Users\\xuefei.lu\\OneDrive - SKEMA Business School\\Research\\JBSHAP\\GermanCredit'
print(path)
os.chdir(path)


import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

import shap as shap_util

#%%
def build_dataset(random_seed):
    dataset = pd.read_csv('german_processed.csv')
    #gender = dataset['Gender']
    dataset = dataset.drop(columns = ['PurposeOfLoan','OtherLoansAtStore']) #
    GoodCustomer = {-1: 0, 1:1}
    dataset = dataset.replace({'GoodCustomer': GoodCustomer})
    Gender = {'Female': 0, 'Male':1}
    dataset = dataset.replace({'Gender': Gender})
    y_raw = dataset['GoodCustomer']
    X_raw = dataset.drop(columns = ['GoodCustomer'])
    
    Xraw_mean = X_raw.mean()
    Xraw_std = X_raw.std()

    # normalize data (this is important for model convergence)
    for k in ['Age','LoanDuration','LoanAmount']:
        X_raw[k] -= X_raw[k].mean()
        X_raw[k] /= X_raw[k].std()
    X_train, X_valid, y_train, y_valid = train_test_split(X_raw, y_raw, test_size=0.2, random_state=random_seed-3)
    #X_train_IfMale = X_train['Gender']
    #X_valid_IfMale = X_valid['Gender']
    #X_train = X_train.drop(columns = ['Gender']) #
    #X_valid = X_valid.drop(columns = ['Gender']) #
    dtypes = list(zip(X_train.dtypes.index, map(str, X_train.dtypes)))
    X_train_array = np.array([X_train[k].values for k,t in dtypes]).T
    X_valid_array = np.array([X_valid[k].values for k,t in dtypes]).T
    return X_train, X_valid, y_train, y_valid, X_train_array, X_valid_array, Xraw_mean, Xraw_std

random_seed = 4321
X_train, X_valid, y_train, y_valid, X_train_array, X_valid_array, Xraw_mean, Xraw_std = build_dataset(random_seed)
#%% load data
file = open('GermanCredit.pkl', 'rb')
BJIshapley = pickle.load(file)
X_target = pickle.load(file)
CFdf = pickle.load(file)
X_target_notfoundCF = pickle.load(file)
CFdf_notfoundCF = pickle.load(file)
X_target_novalidCF = pickle.load(file)
CFdf_novalidCF= pickle.load(file)
X_target_valid= pickle.load(file)
CFdf_valid= pickle.load(file)
InfeasibleInvol= pickle.load(file)
NrMutFeature= pickle.load(file)
CalcTime= pickle.load(file)
BaseShapley= pickle.load(file)
CalcTime_Base= pickle.load(file)
SHAPvalues= pickle.load(file)
file.close()

rename_dict= {
    'LoanDuration':'X1',
    'LoanAmount':'X2', 
    'LoanRateAsPercentOfIncome':'X3',
    'YearsAtCurrentHome':'X4',
    'NumberOfOtherLoansAtBank':'X5', 
    'NumberOfLiableIndividuals':'X6',
    'HasTelephone':'X7',
    'CheckingAccountBalance_geq_0':'X8', 
    'CheckingAccountBalance_geq_200':'X9',
    'SavingsAccountBalance_geq_100':'X10', 
    'SavingsAccountBalance_geq_500':'X11',
    'MissedPayments':'X12',
    'NoCurrentLoan':'X13', 
    'CriticalAccountOrLoansElsewhere':'X14',
    'OtherLoansAtBank':'X15', 
    'HasCoapplicant':'X16', 
    'HasGuarantor':'X17', 
    'Unemployed':'X18', 
    'YearsAtCurrentJob_lt_1':'X19',
    'YearsAtCurrentJob_geq_4':'X20',     
     'Gender':'X21',
     'ForeignWorker':'X22', 
     'Single':'X23', 
     'Age':'X24', 
     'OwnsHouse':'X25',
     'RentsHouse':'X26',
     'JobClassIsSkilled':'X27'
    }
BJIshapley.rename(columns=rename_dict, inplace=True)
BaseShapley.rename(columns=rename_dict, inplace=True)
SHAPvalues.rename(columns=rename_dict, inplace=True)
#%% Figure 6 Absolute Feasible Shapley  -- Gender
sns.set_theme(style="whitegrid")
yrange =  [0, 0.115] 

dfplot0 = BJIshapley.copy()
ylabel = r'Mean |$S_i(\widetilde{\varphi})$|'
plotname1 = 'German_dice_male.pdf'
plotname2 = 'German_dice_female.pdf'

# Figure 6 (a)
dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['Gender']==1).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
fig, axes = plt.subplots(1,1, figsize=(8,4))
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Male',fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname1, format="pdf", bbox_inches="tight")

# Figure 6 (b)
dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['Gender']==0).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Female',fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname2, format="pdf", bbox_inches="tight")
#%% Figure 7 (a) Beewarm Feasible Shapley
dfplot = BJIshapley.copy()
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
X_target_validc = X_target_valid.copy()
X_target_validc.rename(columns=rename_dict, inplace=True)
X_target_validc = X_target_validc.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)

dfplot = dfplot.to_numpy()
shap_util.summary_plot(dfplot, X_target_validc,show=False)
fig, ax = plt.gcf(), plt.gca()
ax.set_xlabel('Feasible Shapley', fontsize = 20 ) #  r'$S_i(\widetilde{\varphi})$'
ax.tick_params(axis='x', labelsize = 20)
ax.tick_params(axis='y', labelsize = 20)
plotname = 'German_dice_beewarm.pdf'
plt.savefig(plotname, format="pdf", bbox_inches="tight")

#%% Figure 7 (b) SHAPs
dfplot = SHAPvalues.copy()
X_target_validc = X_target_valid.copy()
X_target_validc.rename(columns=rename_dict, inplace=True)

dfplot = dfplot.to_numpy()
#dfplot = dfplot.abs()
shap_util.summary_plot(dfplot, X_target_validc,show=False,max_display=28)
fig, ax = plt.gcf(), plt.gca()
ax.set_xlabel('SHAP', fontsize = 20 )
ax.tick_params(axis='x', labelsize = 20)
ax.tick_params(axis='y', labelsize = 20)
plotname = 'German_SHAP_beewarm.pdf'
plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% Figure 13 infeasible points/ nr of feature changed - counterfactual generated by DiCE
sns.set_theme(style="whitegrid")

# Figure 13 (a)
plt.figure(figsize=(6,4))
fig, axes = plt.subplots(1, 1, figsize=(6,4))
axes = sns.histplot(NrMutFeature, binwidth=1)
#axes.set(yscale="log")
axes.set_ylabel ('Count', fontsize = 15)
axes.set_xlabel ('Number of features changed', fontsize = 15)
fig.tight_layout()
plt.show()
# plotname = 'German_NrFeatChanged_dice.pdf'
# plt.savefig(plotname, format="pdf", bbox_inches="tight")
# max(NrMutFeature) 

# Figure 13 (b)
plt.figure(figsize=(6,4))
fig, axes = plt.subplots(1, 1, figsize=(6,4))
axes = sns.histplot(InfeasibleInvol, bins= 25)
axes.set(yscale="log")
axes.set_ylabel ('Count (in log scale)', fontsize = 15)
axes.set_xlabel ('Number of infeasible points', fontsize = 15)
fig.tight_layout()
plt.show()
#plotname = 'German_NrInfeasPoints_dice.pdf'
#plt.savefig(plotname, format="pdf", bbox_inches="tight")
#sum(InfeasibleInvol != 0) # 12
#np.where(InfeasibleInvol != 0)[0]

#%% Figure 17 Absolute Feasible Shapley for Age<=30 or Age >30
sns.set_theme(style="whitegrid")

dfplot0 = BJIshapley.copy()
ylabel = r'Mean |$S_i(\widetilde{\varphi})$|'
plotname1 = 'German_dice_young.pdf'
plotname2 = 'German_dice_old.pdf'

dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid.loc[:,['Age']]*Xraw_std.loc[['Age']]+Xraw_mean[['Age']]<=30).values,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
# 196
fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Age <= 30', fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname1, format="pdf", bbox_inches="tight")


dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid.loc[:,['Age']]*Xraw_std.loc[['Age']]+Xraw_mean[['Age']]>30).values,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)

fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Age > 30', fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname2, format="pdf", bbox_inches="tight")


#%%  Figure 20 Absolute Feasible Shapley for Single and Not Single
dfplot0 = BJIshapley.copy()
ylabel = r'Mean |$S_i(\widetilde{\varphi})$|'
plotname1 = 'German_dice_single.pdf'
plotname2 = 'German_dice_notSingle.pdf'

dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['Single']==1).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
#174

fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Single',fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname1, format="pdf", bbox_inches="tight")

dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['Single']==0).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)# 208

fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('Non Single', fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname2, format="pdf", bbox_inches="tight")

#%% Figure 21 Absolute Feasible Shapley for Rent a house, not rent
dfplot0 = BJIshapley.copy()
ylabel = r'Mean |$S_i(\widetilde{\varphi})$|'
plotname1 = 'German_dice_rent.pdf'
plotname2 = 'German_dice_notrent.pdf'


dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['RentsHouse']==1).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
#103

fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('RentsHouse', fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname1, format="pdf", bbox_inches="tight")


dfplot = dfplot0.abs()
dfplot = dfplot.loc[(X_target_valid['RentsHouse']==0).array,:]
dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)

fig, axes = plt.subplots(1,1, figsize=(8,4))
# Plot the count of male and female
sns.barplot(data=dfplot,ci=95)#ci='sd')
#axes.set_title('No Rent', fontsize = 15)
axes.set_ylabel (ylabel, fontsize = 15)
axes.set_ylim(yrange)
axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
fig.tight_layout()
#plt.show()
plt.savefig(plotname2, format="pdf", bbox_inches="tight")
#%% bar plot - all - feasible Shapley -- NOT USED
# sns.set_theme(style="whitegrid")

# dfplot = BJIshapley.copy()
# dfplot = dfplot.abs()
# #dfplot = dfplot.drop(['Gender','ForeignWorker', 'Single', 'Age', 'OwnsHouse','RentsHouse','JobClassIsSkilled' ], axis=1)
# dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(8,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(data=dfplot,ci=95)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# axes.set_ylim(yrange)
# axes.set_ylabel ('Mean(|Feasible Shapley|)', fontsize = 15)
# fig.tight_layout()
# #plt.show()
# plotname = 'German_dice_all_mean.pdf'
# plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% Barplot - max - Feasible Shapley -- NOT USED
# sns.set_theme(style="whitegrid")
# dfplot = BJIshapley.copy()
# dfplot = dfplot.abs()
# dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
# max_values  = dfplot.max()

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(8,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(x=max_values.index, y=max_values.values)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# axes.set_ylim([0,0.5])
# axes.set_ylabel ('Max(|Feasible Shapley|)', fontsize = 15)
# fig.tight_layout()
# plt.show()
# # plotname = 'German_dice_all_max.pdf'
# # plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% bar plot - all - Baseline (Free) Shapley -- NOT USED
# sns.set_theme(style="whitegrid")
# dfplot = BaseShapley.copy()
# dfplot = dfplot.abs()
# dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(8,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(data=dfplot,ci=95)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# axes.set_ylim(yrange)
# axes.set_ylabel ('Mean(|Baseline Shapley|)', fontsize = 15)
# fig.tight_layout()
# plt.show()
# # plotname = 'German_dice_all_baseline.pdf'
# # plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% Barplot - max - baseline (free) Shapley -- NOT USED
# sns.set_theme(style="whitegrid")
# dfplot = BaseShapley.copy()
# dfplot = dfplot.abs()
# dfplot = dfplot.drop(['X21','X22', 'X23', 'X24', 'X25','X26','X27' ], axis=1)
# max_values  = dfplot.max()

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(8,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(x=max_values.index, y=max_values.values)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# axes.set_ylim([0,0.5])
# axes.set_ylabel ('Max(|Baseline Shapley|)', fontsize = 15)
# fig.tight_layout()
# plt.show()
# # plotname = 'German_dice_all_max_baseline.pdf'
# # plt.savefig(plotname, format="pdf", bbox_inches="tight")

#%% bar plot - all - SHAP --  NOT USED
# sns.set_theme(style="whitegrid")
# dfplot1 = SHAPvalues.copy()
# dfplot1 = dfplot1.abs()
# mutable_column_names = [f'X{i+1}' for i in range(20)]
# dfplot1 = dfplot1.loc[:,mutable_column_names]


# dfplot2 = SHAPvalues.copy()
# dfplot2 = dfplot2.abs()
# UnmutableFeatures = [f'X{i+1}' for i in range(20,27)]
# dfplot2 = dfplot2.loc[:,UnmutableFeatures]

# dfplot = pd.concat([dfplot1, dfplot2], axis=1)

# # Generate the first 20 colors from the 'deep' palette
# deep_palette = sns.color_palette('husl', 20)
# # Generate the next 7 colors from the 'pastel' palette
# pastel_palette = sns.color_palette('pastel', 7)
# # Combine the two palettes
# combined_palette = deep_palette + pastel_palette
# # Set the combined palette
# sns.set_palette(combined_palette)

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(12,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(data=dfplot,ci=95,palette=combined_palette)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# # Add a vertical line between the 20th and 21st bars
# plt.axvline(x=19.5, color='black', linestyle='--')
# axes.set_ylabel ('Mean(|SHAP|)', fontsize = 15)
# fig.tight_layout()
# plt.show()
# # plotname = 'German_dice_all_SHAP.pdf'
# # plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% Barplot - max - SHAP -- NOT USED
# sns.set_theme(style="whitegrid")
# dfplot1 = SHAPvalues.copy()
# dfplot1 = dfplot1.abs()
# mutable_column_names = [f'X{i+1}' for i in range(20)]
# dfplot1 = dfplot1.loc[:,mutable_column_names]
# max_values1  = dfplot1.max()

# dfplot2 = SHAPvalues.copy()
# dfplot2 = dfplot2.abs()
# UnmutableFeatures = [f'X{i+1}' for i in range(20,27)]
# dfplot2 = dfplot2.loc[:,UnmutableFeatures]
# max_values2  = dfplot2.max()

# dfplot = pd.concat([max_values1, max_values2])

# # Generate the first 20 colors from the 'deep' palette
# deep_palette = sns.color_palette('husl', 20)
# # Generate the next 7 colors from the 'pastel' palette
# pastel_palette = sns.color_palette('pastel', 7)
# # Combine the two palettes
# combined_palette = deep_palette + pastel_palette
# # Set the combined palette
# sns.set_palette(combined_palette)

# # create the bar plot with error bars
# fig, axes = plt.subplots(1, 1, figsize=(12,4))
# sns.set_theme(style="whitegrid")
# axes = sns.barplot(x=dfplot.index, y=dfplot.values,palette=combined_palette)
# axes.tick_params(axis='y',labelsize = 15)
# axes.tick_params(axis='x', labelrotation=90,labelsize = 15)
# # Add a vertical line between the 20th and 21st bars
# plt.axvline(x=19.5, color='black', linestyle='--')
# axes.set_ylabel ('Max(|SHAP|)', fontsize = 15)
# fig.tight_layout()
# plt.show()
# # plotname = 'German_dice_all_max_SHAP.pdf'
# # plt.savefig(plotname, format="pdf", bbox_inches="tight")
#%% partial dependent plot -- NOT USED
# plotindex = 4
# colorindex = 4
# dfplot = pd.DataFrame()
# dfplot[features_to_vary[plotindex]] =  X_target_valid.loc[:, features_to_vary[plotindex] ] 
# dfplot['Constrined Shapley'] =  BJIshapley.loc[:, features_to_vary[plotindex] ].values
# dfplot['color'] =  BJIshapley.loc[:, features_to_vary[colorindex] ].values

# plt.figure(figsize=(8, 6))
# #sns.set()
# sns.set_theme(style="whitegrid")
# cmap_reversed = plt.colormaps.get_cmap('RdBu_r')
# ax = sns.scatterplot(x=features_to_vary[plotindex], y='Constrined Shapley', hue="color",
#                      palette=cmap_reversed, data=dfplot)

# norm = plt.Normalize(dfplot['color'].min(), dfplot['color'].max())
# sm = plt.cm.ScalarMappable(cmap=cmap_reversed, norm=norm) #RdBu
# sm.set_array([])

# # Remove the legend and add a colorbar
# ax.get_legend().remove()
# ax.figure.colorbar(sm, label = features_to_vary[colorindex] )
# #cbar = ax.figure.colorbar(sm)
# #cbar.set_label(features_to_vary[colorindex] )  # Add a label to the color bar

# #sns.histplot(dfplot[features_to_vary[plotindex]], color='gray', stat='probability',fill=True)
# #plt.show()
# plotname = 'German_partial_dependent_'+features_to_vary[plotindex]+'.pdf'
# plt.savefig(plotname, format="pdf", bbox_inches="tight")